server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db
    baseline-on-migrate: true
    schemas: public
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      enabled: true